### PR TITLE
No such bucket flagfix

### PR DESCRIPTION
**Pull request by khuddlefish**
When this option is `true` we will add a handler to modify the s3 endpoint and
remove a duplicate bucket in order to support a customer use case where they
were getting NoSuchBucket errors

A benefit of this option is we won't have to make extra API calls each time to test and retry

### CODE REVIEW

**Comment by kyeap-vmware** [comment]
I had an idea I want to float to you.

What are your thoughts about taking one step further and auto toggle when applicable? Workflow would look like this.
1. s3 plugin runs normally.
2. if normal upload/download fails try remove bucket fix.
3. if bucket fix upload/download succeed, rewrite the config file on the host to turn on "remove_duplicate_bucket"

Then every subsequent s3 call for that backup/restore would then use the fix. Craig doesn't have to worry about the new option. It turns on by itself. Modifying the original config file isn't a foreign concept. gpbackup adds additional options to plugin config files in createHostPluginConfig. One thing we would need to worry about is multiple s3 plugins trying to modify the host's config file.

Main point of this would be to keep the option hidden from the users.

**Comment by khuddlefish** [comment]
> I had an idea I want to float to you.
> 
> What are your thoughts about taking one step further and auto toggle when applicable? Workflow would look like this.
> 
> 1. s3 plugin runs normally.
> 2. if normal upload/download fails try remove bucket fix.
> 3. if bucket fix upload/download succeed, rewrite the config file on the host to turn on "remove_duplicate_bucket"
> 
> Then every subsequent s3 call for that backup/restore would then use the fix. Craig doesn't have to worry about the new option. It turns on by itself. Modifying the original config file isn't a foreign concept. gpbackup adds additional options to plugin config files in createHostPluginConfig. One thing we would need to worry about is multiple s3 plugins trying to modify the host's config file.
> 
> Main point of this would be to keep the option hidden from the users.

Hmm I'm trying it out and the implementation seems pretty messy. I think editing the config file will have more complicated code than either of the other two options since the code needs to add the config option and then we'll need some retry logic to try it first with the option (whether it's off or on) and retry with the other. And also editing the file will be messy since we'll need some kind of lock file.

I'm kind of liking the simplicity of the config option. Most users won't need to touch it, but if they get the error they can either see it in the docs or raise a support ticket and we can suggest for them to turn it on. It's a pretty quick adjustment on the customer side to run it once, see it fail and then just edit the config and it should work after. Kind of like how we use some gpdb gucs.

**Comment by kyeap-vmware** [comment]
Do we also need to bring back the change that only edited the path if not an IP address?
```
* 10a4b72 - (tag: 1.10.1) Only remove bucket name if not an IP (7 months ago) <Andrew Repp>
* bce4362 - Alter path for endpoint configs (7 months ago) <Andrew Repp>
```

**Comment by khuddlefish** [comment]
> Do we also need to bring back the change that only removed bucket name if not an IP address?
> 
> ```
> * 10a4b72 - (tag: 1.10.1) Only remove bucket name if not an IP (7 months ago) <Andrew Repp>
> * bce4362 - Alter path for endpoint configs (7 months ago) <Andrew Repp>
> ```

No. That only applies if we're trying to do it automatically. If it's fully configured by the user flag it should just do it when the user specifies. They can toggle it on or off to properly handle IP addresses if needed. I'm guessing that for most users they're going to have a certain way of using it for their setup. Whether that be endpoint, region, IP, etc. They should be able to develop a config that works for their system and just keep it. So I doubt they'll need to change this value once they have something that works.

**Review by kyeap-vmware — APPROVED** [review]
LGTM.

**Pull request merged**
